language: csharp

matrix:
  include:
#Nightly builds for upload. Use lowest possible Mono version for compatibility purposes
    - os: linux
      dist: precise
      mono: 3.2.8
      script: make publish
    - os: osx
      mono: latest
      before_install: if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install leezer3/sshpass/sshpass; fi;
      script: make publish

#Test builds
##Use makefile##
    - os: linux
      dist: trusty
      mono: latest
      script: make all-release
    - os: osx
      mono: latest
      before_install: if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install leezer3/sshpass/sshpass; fi;
      script: make all-release
    - os: linux
      dist: precise
      mono: 3.2.8
      script: make all-release
##Use .sln file##
    - os: linux
      dist: precise
      mono: latest
      solution: OpenBVE.sln
    - os: linux
      dist: trusty
      mono: latest
      solution: OpenBVE.sln
    - os: osx
      mono: latest
      before_install: if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew install leezer3/sshpass/sshpass; fi;
      solution: OpenBVE.sln
    - os: linux
      dist: precise
      mono: 3.2.8
      solution: OpenBVE.sln
 
after_success:
#Export SSH password for whichever platform we are building on
 - test $TRAVIS_PULL_REQUEST == "false" && (test $TRAVIS_BRANCH == "master" || test $TRAVIS_TAG) && export SSHPASS=$DEPLOY_PASS
#Nightly build
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test "$TRAVIS_OS_NAME" == "linux" && mv "linuxbuild.zip" "OpenBVE-$(date '+%F').zip"
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test "$TRAVIS_OS_NAME" == "linux" && ./UploadScript.sh sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "OpenBVE-$(date '+%F').zip" $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
#Release build
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "linux" && mv "linuxbuild.zip" "openBVE-$TRAVIS_TAG.zip"
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "linux" && ./UploadScript.sh sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "openBVE-$TRAVIS_TAG.zip" $DEPLOY_USER@$DEPLOY_HOST:$RELEASE_PATH
#Create deb and push that too on releases
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "linux" && make debian
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "linux" && mv "installers/debian.deb" "openBVE-$TRAVIS_TAG.deb" 
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "linux" && ./UploadScript.sh sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "openBVE-$TRAVIS_TAG.deb" $DEPLOY_USER@$DEPLOY_HOST:$RELEASE_PATH
##OSX Builds##
#Nightly build
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test "$TRAVIS_OS_NAME" == "osx" && mv "macbuild.dmg" "OpenBVE-$(date '+%F').dmg"
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test "$TRAVIS_OS_NAME" == "osx" && ./UploadScript.sh sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "OpenBVE-$(date '+%F').dmg" $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
#Release build
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "osx" && mv "macbuild.dmg" "openBVE-$TRAVIS_TAG.dmg"
 - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_TAG && test "$TRAVIS_OS_NAME" == "osx" && ./UploadScript.sh sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "openBVE-$TRAVIS_TAG.dmg" $DEPLOY_USER@$DEPLOY_HOST:$RELEASE_PATH
addons:
  apt:
    packages:
      - sshpass
      - p7zip-full
      - fakeroot
env:
  global:
    - secure: "NquGr/vI8CyhAV5itzUxV5gXCtWFn3kqOnAeEz5Niw4fJfrBH5G/TBGyQpyzkpeY+Tox8z8m+a/UdSYutVxI9OYbAuFH8vo75pL3oydFtNOnuO45v4BFaz9KLGB0AEAvNzX7YTUM7qEE4QlX2/jzPXSoJqxC9RWMdENxwjzCvE0CLhBPQvqCSxB6nJ86rRM7xpLkT34t+C66XjdHSLKDcu94dC50o8MxnIchgWAfEV4+d9kv6XZV+rZvz75e8qYzCJKU6wl3GPMpL8JajG3TIkHAiNWPlcH8WbCqd62znZYtFUMvVkFDKOAjnq1sMqMYfFiu3x+AJPYF52Se2g5qDrkOCZhKL2MSofEugvSjlNekkfQzg/SqHJXlToZvvWQWvuZaTcjYwoiFg+O0eFgvN1bjX2Z7Y9Pb85o+DgKn0WFkBkCohbygFw1Iir1tT5+3bnt3uAZWPKH8k7r5+Tbm2KxJ3O0/ietbMW97S9EaU24Gwh6YbPRVskEgp3ym/2It0sgMfEb64GnhbvGG6lPk3uU6AEmmxHsBgxv+E2ZdRVOqEsWVeBs8IDmVwXeG8T1FCL+GtV5hTwmIMH+z+OTuAHEzKR81DohF+z3vXzYOLxzSCx9IBKkTfIiVKpuFl6+l17olIgaGwomN23b6p0Eky0ZRrWupjkoetIJF6A9Ux8M="
    - secure: "MENrO/nw7Qon6cgCPF4WMWzzSzZK368ZpetdP0cO4Mijmxa+LoLYONl7cxGgwj9IdreVyJXuriKAUuiAcLhd74MVjoMrfsfmPA3veDXTj+lGTF5JpL8NR+eyax4joOEiv7VNPnemNU35v2s6SaiofSGuCcvag0gIBxmMQ8OaZNCDtUSaM4pj71AXOBpAKU7+j1dW2QVfk1xt9MvluR9/Xp51kN3HlFD1iowSNRf3hY9xnFKR+5iAv+1fx4ZVJzm0A8Gx7YWUZ5taYXm11ozG/9UbTSIZOh0676AKax10Ur+iUTqVvB6fTQzNINaRA7wu/BEpWE1gV4cUgMzZZTh31PtzfxwFrsSsdwSDbkdzUgmMW+ifdqJDxOBfRGslOYDNYEA3iFBNi3gWQ3T36qxyFvST98teB+UXcs40bQ/E9yV73pdRXRp0+WPbQevVHCh/wia/3CSoNsX5KonvhRkgm2D4oPqfSJmejqkdsEW2XnAqP+P2q77n81Fi+IVcejZG07ORco+oiHVVjfnmiYy100/yg63SDwNKBDbiGcY7ngSsnKPyYunTLOqeNzJ2hpnyUIs/qHedZYSOGJs5BCSsHE/zrFcQSNjjhmdkxLj7vpCyCWCWEg4pgzFbhxScKUhJ6he/J3kb60x4JrSfkFg+pScQboeoYQaRvRp50MhlB6s="
    - secure: "01QIDNccjTagPaT6ZxzBO2qCA65ju6hImlcMia8bZoDT2ufWtxhN94RiZA9WN0jQ8fCnbXFW3HVUWywrb9OblJXAGBW9pxrTGTbSkVm5eMfgEII2RTxW0yWfnWajhm0TnK0wFHVT6eP72gZrv9C2ieAikZdXaNQKa+wlnLPaiEeFUz/8KgaK85ANJ3j1PQ4mhMJ3po9uchAmfF4xsWfoJGth+hXAN16UMCKbbTFqtTdEhecdTh2PiE64O1yJTL9E5WXDD6mxXZi/gsGaFbLQQNS9v+CyGuNafWggTNKI9FwN9/i85MS+0UmD0aParkCoBN6HTiEHqW0KgCH9C3qxLBN5hlB+C+4r92/jeC31NU6OFi/Fh722qBPQs2dmm+O3dKRb1bgJ7KzhGIJRuFa+GhqoyIJejWFmishEouLdDrAPr1hW8h4SP2WtPir+3wTrqoSHIt6VvpF0jy2oKFiSKl5bOdC3UAq1V04gNUeq6giUTL56XfPyLOOimwchGR6VnZ1JTc0TPdaA+R7qaAMZhm26QZI05O6fWkhtiLjOhf1JQVY47oUwIyIJB7nczTeZtYeetWdRCSmAvXUyIMRbTaqy8QsQPtuNfzWj4iuaSPez8G6xUcN1qKZchaOFLOSv9UeNvaq624M0M/nT1JEbhLknASRa6UinJeLAbezNFTk="
    - secure: "A/0AimkzkRNbOW8OjymGx6gR5tbGDvSz3An1Wwco5nqSrDaZebG0viFtYcLX1RmZ9aqS4Hr8v9ksi1Chu1nE9Swp/VQeMgDRUTi4jEzytJpUvIpHJWFJ/Pn7XoXHanLHqDaj2A8oEZSx8doFvTIN8a9ousP/xJYp9a9xo33ulBkTVftalgyCvhYfz+a9BeDVlgL9/IBNfAT3fY+c+P8l/AjgWF6oN0rYAiDQHsxx8kQQxboZihAYTbkSonxbF5BgoLjKpAmPOkMT3oWat5GXKH/6yHfk+JIBaATSQqUik8VNqoyO7rIGz68Jodhs5PDHfENrZ17FIt0/lpjE6l/3oHwzs/RhgyD64x2bEf/KeVqJ7+R0kvgTVdg2pjpb4AHc8SGk1ARoDWvCdRPcM+Sii9iavJQtCuTDir24DNzknHxvnqlR8vUsYFBOhfcMTL1y/2tNJY9NiH39bkJsGLz8NqAipC+IoR7Jm4WhEgemAfnpicrOjZVAUL6sGwHIg99MSKAMpliXvqE/EAlY0aWYnx2W6HuFy3g2cCJ16JJABJFDK/H6a1V485naI9DT4/nHXJjuweN0ijm9jBpDMpIJ9E3uyDXBkjWGkxmIE9HPYdiJIdGqxQ5SzaN8XmRLRo6AQnsDX243TurWld7hXcyktVFXxsHUmAMpN0tR3EJcJQM="
    - secure: "xhY40lPWCokuabAfN7t2gd4DTrNXpxvKiH6Xobo5XkAiDNseBw+MZ/ce4XZeAXnq9jHdeTXVMu1rtcdFlC5St2XCeltNpchS4Km8dv+7ErtTBAawgl+5rGwTTnIF5jUTPsbzfEcIgnL6ud7NWDEqYQm5oeEMpuS3z/gqSc/HKx3Fp5cIPte65Oo37oMuL0dwNh2XIwrogaSOHX+Jwh7B5ZkCMzAe/MOxg0b34A4noAtCHbtc2QmmDhOhdlk+OBx5iSIwqUvmW8YYUX+14mIFAqWQ6E7MOUY9gjDgedXnbfvPsw+gLeXyCoNunc980EMdrIF2KHaPa772TFi7MzOiPwXno2jxlK3INvGylYdymI4YwI97H53oasfT1RiOzG9j1zCqJZv3U1L5KdscX8LKPYXsOeP78okB5lXt2E2jiO7hVJMIhQtJrNiCmlok3/U65jD30WLBsZtIBzZ4RhpESYr2a5QayhFmbHmIeMbfhY6OkRiE/enCMYuCFlnV6twWA4J6gBUVilYj+qjR6Js2xRAtaY0ljnPhK0EE2RIjPOKks3CPlchP3ZbI9jFCaupBfLlT0uBfmMu0aD/q/AZ0wDf1Dp1OdRzGbBcvhDcijpmZ8GatLyZS64Iq27WqUC6XouI17SIj0XftnBkcKTbSXY9UbSXM2bPYuHLIGk61aXU="
notifications:
      email: false
